App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^hello/', views.hello),
    url(r'^index/', views.index),
    url(r'^getstudents/', views.get_students),
    url(r'^temp/', views.temp),
    url(r'^home/', views.home),
    url(r'^hehe', views.hehe),
    url(r'^hehehe', views.hehehe),
]

DjangoTemlate/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls')),
    url(r'^more/', include('Two.urls', namespace='second')),
]

Two/urls.py
from django.conf.urls import url

from Two import views

urlpatterns = [
    # url(r'^students/(\d+)/', views.student),

    url(r'^grades/', views.grades),
    url(r'^students/(\d+)/', views.students),
    url(r'^gettime/(\d+)/(\d+)/(\d+)/', views.get_time, name='get_time'),
    url(r'^getdate/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/', views.get_date, name='get_date'),

    url(r'^learn/', views.learn, name='learn'),

    url(r'^haverequest/', views.have_request),

    url(r'^createstudent/', views.create_student),

    url(r'^docreatestudent/', views.do_create_student, name='do_create_student'),
]

App/models.py
from django.db import models


class Student(models.Model):
    s_name = models.CharField(max_length=16)

    def get_name(self):
        return self.s_name

Two/models.py
from django.db import models


class Grade(models.Model):
    g_name = models.CharField(max_length=16)


class Student(models.Model):
    s_name = models.CharField(max_length=16)
    s_grade = models.ForeignKey(Grade)

App/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

from App.models import Student


def hello(request):
    return HttpResponse("Hello")


def index(request):
    # 本质上也是返回的HttpResponse，   它帮我们把模板和context数据 渲染成字符串
    # return render(request, 'index.html')

    # 见名知意

    temp = loader.get_template('index.html')

    content = temp.render()

    return HttpResponse(content)


def get_students(request):

    students = Student.objects.all()

    student_dict = {
        "hobby": "coding",
        "time": "one year"
    }

    code = """
            <h2>睡着了</h2>
            <script type="text/javascript">
                var lis = document.getElementsByTagName("li");

                for (var i=0; i< lis.length; i++){
                    var li = lis[i];
                    li.innerHTML="日本是中国领土的一部分!";
                }
            </script>
    """

    data = {
        "students": students,
        "student_dict": student_dict,
        "count": 5,
        "code": code
    }

    return render(request, 'student_list.html', context=data)


def temp(request):
    return render(request, 'home.html', context={"title": "home"})


def home(request):
    return render(request, 'home_mine.html')


def hehe(request):
    return HttpResponse("呵呵你个大头鬼")


def hehehe(request):
    return HttpResponse("Drink")

Two/views.py
from django.http import HttpResponse
from django.shortcuts import render

from Two.models import Grade, Student


def students(request, g_id):

    student_list = Student.objects.filter(s_grade_id=g_id)

    return render(request, 'grade_student_list.html', context=locals())


def student(request):

    # print(s_id)
    #
    # print(type(s_id))

    return HttpResponse("Get Student Success")


def grades(request):

    grade_list = Grade.objects.all()

    # locals

    return render(request, 'grade_list.html', context=locals())


def get_time(request,hour, minute, second):
    return HttpResponse("Time %s: %s: %s" %(hour, minute, second))


def get_date(request,  month, day, year):
    return HttpResponse("Date %s- %s- %s" %(year, month, day))


def learn(request):
    return HttpResponse("Love Learn")


def have_request(request):

    print(request.path)

    print(request.method)

    print(request.GET)

    hobby = request.GET.get('hobby')

    print(hobby)

    hobbies = request.GET.getlist('hobby')

    print(hobbies)

    print(request.POST)

    # print(request.META)

    # for key in request.META:
    #     print(key, request.META.get(key))

    print("Remote IP", request.META.get("REMOTE_ADDR"))

    return HttpResponse("Request Success")


def create_student(request):
    return render(request, 'student.html')


def do_create_student(request):

    print(request.method)

    username = request.POST.get('username')

    return HttpResponse(username)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block ext_css %}

    {% endblock %}
</head>
<body>

<h1>他们的声音好大啊！</h1>

{% block header %}

{% endblock %}

{% block banner %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<h4>本网站受美国法律保护！XXX</h4>

templates/grade_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GradeList</title>
</head>
<body>

<ul>
    {% for grade in grade_list %}
        <li><a href="/two/students/{{ grade.id }}/">{{ grade.g_name }}</a></li>
    {% endfor %}

</ul>


<hr>
<a href="/two/learn/">Go Learn</a>

<hr>

<a href="{% url 'second:learn' %}">Go Go Go</a>

<hr>
<a href="{% url 'second:get_time' 15 31 48 %}">Time Time</a>

<hr>

<a href="{% url 'second:get_date' year=2018 month=9 day=19 %}">Date Date</a>

</body>
</html>

templates/grade_student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GradeStudentList</title>
</head>
<body>

    <ul>
        {% for student in student_list %}
            <li>{{ student.s_name }}</li>
        {% endfor %}

    </ul>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block header %}
    <h3>哈哈哈，这是一个头</h3>
{% endblock %}

templates/home_mine.html
{% extends 'home.html' %}
{% load static %}

<h3>今天今天是个适合睡觉的日子！</h3>

{% block content %}
    <h3>哈哈哈，你就是这么强大</h3>
{% endblock %}

{% block header %}
    {{ block.super }}
    <h4>听说你很精神！</h4>
{% endblock %}


{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

{% block ext_css %}
{#    <link rel="stylesheet" href="/static/css/home_mine.css">#}
    <link rel="stylesheet" href="{% static 'css/home_mine.css' %}">
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

<h3>今天大家状态不错啊!</h3>

</body>
</html>

templates/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student</title>
</head>
<body>

<form action="{% url 'second:do_create_student' %}" method="post">

    <span>Username:</span> <input type="text" name="username" placeholder="Please input username">

    <button>Submit</button>

</form>


</body>
</html>

templates/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StudentList</title>

</head>
<body>

<ul>
    {% for student in students %}
        <li>{{ student.s_name }}</li>
    {% empty %}
        <h1>Sunck辍学了</h1>
    {% endfor %}

</ul>

<hr>

<ul>
    {% for student in students %}
        <li>{{ forloop.revcounter }}:{{ student.get_name }}</li>
    {% endfor %}

</ul>

<hr>
<h3>{{ students.1.s_name }}</h3>

<hr>

<h3>{{ student_dict.hobby }}</h3>
<h3>{{ student_dict.hobby|lower }}</h3>
<h3>{{ student_dict.hobby|upper }}</h3>

<hr>
<ul>
    {% for student in students %}
        {% if forloop.first %}
            <li style="color: red">{{ student.s_name }}</li>
        {% elif forloop.last %}
            <li style="color: green">{{ student.s_name }}</li>
        {% else %}
            <li>{{ student.s_name }}</li>
        {% endif %}
    {% endfor %}

</ul>

<hr>

<!--
    老板说让咱们把第一版写的卡一点，等客户交钱优化，我们给他提升一下响应速度
    time.sleep(3)
-->

<h4>{{ count }}</h4>
<h4>{% widthratio count 1 5 %}</h4>
<h4>{% widthratio count 5 1 %}</h4>
<h4>{{ count|add:2 }}</h4>
<h4>{{ count|add:-2 }}</h4>

{#  打不到我吧，哈哈哈  #}

{% comment %}
    <ul>
        <li>xxx</li>
    </ul>
{% endcomment %}

<hr>

<ul>
    {% for student in students %}
        {% if forloop.counter|divisibleby:3 %}
            <li style="color: #ff0000">{{ student.s_name }}</li>
            {% else %}
            <li style="color: #b228ff;">{{ student.s_name }}</li>
        {% endif %}
    {% endfor %}

</ul>

<hr>
<ul>
    {% for student in students %}
        {% ifequal forloop.counter 5 %}
            <li style="color: orange">{{ student.s_name }}</li>
            {% else %}
            <li style="color: blue">{{ student.s_name }}</li>
        {% endifequal %}
    {% endfor %}

</ul>

<hr>
{#<p>{{ code|safe }}</p>#}

{% autoescape on %}
    {{ code }}
{% endautoescape %}

</body>
</html>